// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_ZFgW57y_D9_hB2xqpjQ0VvlKPoSWdLY',
    appId: '1:556139801769:web:9176f28131261ca32b8db8',
    messagingSenderId: '556139801769',
    projectId: 'app-aranda',
    authDomain: 'app-aranda.firebaseapp.com',
    databaseURL: 'https://app-aranda-default-rtdb.firebaseio.com',
    storageBucket: 'app-aranda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4qqlF7CFvTsxAhKxEgj6F55TVUVHcIuw',
    appId: '1:556139801769:android:cdf08ca6e32e95a72b8db8',
    messagingSenderId: '556139801769',
    projectId: 'app-aranda',
    databaseURL: 'https://app-aranda-default-rtdb.firebaseio.com',
    storageBucket: 'app-aranda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjcjQU9O3UB7bESmmu7Wl6Dbd6F9BRIsw',
    appId: '1:556139801769:ios:2d0f4ca30804627e2b8db8',
    messagingSenderId: '556139801769',
    projectId: 'app-aranda',
    databaseURL: 'https://app-aranda-default-rtdb.firebaseio.com',
    storageBucket: 'app-aranda.appspot.com',
    iosBundleId: 'com.example.proyecto01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjcjQU9O3UB7bESmmu7Wl6Dbd6F9BRIsw',
    appId: '1:556139801769:ios:2d0f4ca30804627e2b8db8',
    messagingSenderId: '556139801769',
    projectId: 'app-aranda',
    databaseURL: 'https://app-aranda-default-rtdb.firebaseio.com',
    storageBucket: 'app-aranda.appspot.com',
    iosBundleId: 'com.example.proyecto01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_ZFgW57y_D9_hB2xqpjQ0VvlKPoSWdLY',
    appId: '1:556139801769:web:e8816e96017305612b8db8',
    messagingSenderId: '556139801769',
    projectId: 'app-aranda',
    authDomain: 'app-aranda.firebaseapp.com',
    databaseURL: 'https://app-aranda-default-rtdb.firebaseio.com',
    storageBucket: 'app-aranda.appspot.com',
  );

}